language: node_js
node_js:
  - "11"

sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push navicore/www.onextent.com;
    docker tag "navicore/www.onextent.com" "navicore/www.onextent.com:0.1.$TRAVIS_BUILD_NUMBER";
    docker push "navicore/www.onextent.com:0.1.$TRAVIS_BUILD_NUMBER";
    fi

